added the source code
hazelops/terraform-aws-route53-healthcheck pull request #1
Opened 2020-09-29 20:25 UTC by igorkotof

Added source code of the module

2020-09-29 20:28 UTC, igorkotof commented
![](https://github.trello.services/images/mini-trello-icon.png) [Create terraform-aws-route53-healthcheck opensource module](https://trello.com/c/CDoXo67N/124-create-terraform-aws-route53-healthcheck-opensource-module)

2020-10-01 13:32 UTC, AutomationD requested changes

2020-10-01 13:32 UTC, AutomationD commented on README.md
> +We will monitore s3-static-website.s3-website-us-east-1.amazonaws.com with PagetDuty notification with
`monitor` typo.

2020-10-01 13:32 UTC, AutomationD commented on README.md
> +* (optional) Secondary Route53 record for failover routing policy to public S3 website with "Maintenance page"
Let's add information about s3 bucket?

2020-10-01 13:32 UTC, AutomationD commented on versions.tf
> +  required_version = ">= 0.13"
Can we make this compatible with 0.12 (even if with warnings)?

2020-10-01 14:12 UTC, igorkotof commented
@AutomationD Resolved all comments - Thanks!

2020-10-01 14:15 UTC, igorkotof commented
@AutomationD fixed  :) sorry

2020-10-01 18:58 UTC, merged